export const TYPES = {
  SET_MAIN_INFO : 'SET_MAIN_INFO',
  SET_FULL_TEMP_DATA: 'SET_FULL_TEMP_DATA',
  SET_SOME_DATA: 'SET_SOME_DATA',
  SET_DATA_FILLED_INFO: 'SET_DATA_FILLED_INFO',
  SET_PAGE_AND_LIMIT: 'SET_PAGE_AND_LIMIT'
}